export const CLIENT_LIST = "CLIENT_LIST";
export const CLIENT_PROFILE = "CLIENT_PROFILE";

export const SETTINGS_AGENT = "SETTINGS_AGENT";
export const SETTINGS_PRJGRP = "SETTINGS_PRJGRP";
export const SETTINGS_TRANSTYPE = "SETTINGS_TRANSTYPE";
