export const CLIENT_LIST = "CLIENT_LIST";
export const CLIENT_PROFILE = "CLIENT_PROFILE";
export const CLIENT_SUMMARY = "CLIENT_SUMMARY";
export const PAYMENT_LIST = "PAYMENT_LIST";
export const PAYMENT_TRANSACTION = "PAYMENT_TRANSACTION";
export const PAYMENT_RECORDS = "PAYMENT_RECORDS";
export const TRANSACTION_LIST = "TRANSACTION_LIST";

export const SETTINGS_AGENT = "SETTINGS_AGENT";
export const SETTINGS_PRJGRP = "SETTINGS_PRJGRP";
export const SETTINGS_TRANSTYPE = "SETTINGS_TRANSTYPE";
export const SETTINGS_CATEGORY = "SETTINGS_CATEGORY";
